#!/bin/bash

# ╔═══════════════════════════════════════════════════════════════╗
# ║    🚀 AI ACCOUNTANT - БЫСТРЫЙ ДЕПЛОЙ (Копируй и выполняй)    ║
# ╚═══════════════════════════════════════════════════════════════╝

echo "🚀 AI Accountant - Быстрый деплой"
echo ""
echo "Выберите способ деплоя:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  VERCEL (Рекомендуется)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Через GitHub (автоматический деплой):"
echo "   1. Создайте репозиторий: https://github.com/new"
echo "   2. Выполните:"
echo ""
echo "      git remote add origin https://github.com/USER/REPO.git"
echo "      git branch -M main"
echo "      git push -u origin main"
echo ""
echo "   3. https://vercel.com → Add Project → Import Git"
echo ""
echo "   Или через CLI (прямо сейчас):"
echo ""
echo "      npx vercel login"
echo "      npx vercel --prod"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  NETLIFY (Альтернатива)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Через GitHub:"
echo "   1-2. То же, что для Vercel"
echo "   3. https://netlify.com → Add Site → Import Git"
echo ""
echo "   Или через CLI:"
echo ""
echo "      npx netlify-cli login"
echo "      npx netlify-cli deploy --prod --dir=dist"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  GITHUB PAGES (Бесплатно)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   npm install --save-dev gh-pages"
echo "   npm run deploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Подробности: читайте DEPLOY_NOW.md"
echo ""
