// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: transaction.
// - Entity ID: 102019ae94a70957797955090c3e0b654c6.
// - Entity Version: 102019b505b2cc97c4e87e620b193838a68.
// - Task ID: 694bdde12e0faedc96c1c26c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for TransactionType
 */
export enum TransactionType {
  Unspecified = 0,
  Income = 1,
  Expense = 2,
}



/**
 * Interface for TransactionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TransactionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  bank_account_id?: string | null;
  type: TransactionType;
  category: string;
  amount: number;
  description?: string | null;
  date: string;
  sync_status: string;
  version: number;
  is_deleted: boolean;
}

/**
 * ORM class for Transaction entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TransactionORM {
  private static instance: TransactionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ae94a70957797955090c3e0b654c6';
    this.entityName = 'transaction';
    this.entityVersion = '102019b505b2cc97c4e87e620b193838a68';
    this.taskId = '694bdde12e0faedc96c1c26c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of TransactionORM
   */
  public static getInstance(): TransactionORM {
    if (!TransactionORM.instance) {
      TransactionORM.instance = new TransactionORM();
    }
    
    return TransactionORM.instance;
  }

  /**
   * Get transaction by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getTransactionByIDs(ids: string[]): Promise<TransactionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteTransactionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Transaction records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTransaction(): Promise<TransactionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Transaction record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTransaction(data: TransactionModel[]): Promise<TransactionModel[]> {
    const structured = data.map((item) => CreateData(TransactionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Transaction records
   */
  async purgeAllTransaction(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Transaction records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTransaction(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TransactionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get transaction by Id index
   * This function gets data by index.
   */
  async getTransactionById(
    id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionById(
    id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexId(
      id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by Id index
   */
  async deleteTransactionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DateUserId index
   * This function gets data by index.
   */
  async getTransactionByDateUserId(
    date: string,
    user_id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDateUserId(
    date: string,
    user_id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DateUserId index
   */
  async deleteTransactionByDateUserId(
    date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexDateUserId(
      date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by BankAccountId index
   * This function gets data by index.
   */
  async getTransactionByBankAccountId(
    bank_account_id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexBankAccountId(
      bank_account_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by BankAccountId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByBankAccountId(
    bank_account_id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexBankAccountId(
      bank_account_id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by BankAccountId index
   */
  async deleteTransactionByBankAccountId(
    bank_account_id: string
  ): Promise<void> {
    const index = createIndexBankAccountId(
      bank_account_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DataCreator index
   * This function gets data by index.
   */
  async getTransactionByDataCreator(
    data_creator: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDataCreator(
    data_creator: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DataCreator index
   */
  async deleteTransactionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DataUpdater index
   * This function gets data by index.
   */
  async getTransactionByDataUpdater(
    data_updater: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDataUpdater(
    data_updater: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DataUpdater index
   */
  async deleteTransactionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TransactionModel data array
   */
  private resultToData(values: Data[]): TransactionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TransactionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TransactionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TransactionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TransactionModel => item !== null);
  }
}

/**
 * Convert TransactionModel data to Value array
 */
function TransactionModelToValues(data: TransactionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'bank_account_id', type: DataType.string, defaultValue: null },
    { key: 'type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'category', type: DataType.string, defaultValue: '' },
    { key: 'amount', type: DataType.number, defaultValue: 0 },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'date', type: DataType.string, defaultValue: '' },
    { key: 'sync_status', type: DataType.string, defaultValue: '' },
    { key: 'version', type: DataType.number, defaultValue: 0 },
    { key: 'is_deleted', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TransactionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TransactionModel data
 */
function TransactionModelFromValues(values: Value[]): TransactionModel {
  const data: Partial<TransactionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'bank_account_id':
        data.bank_account_id = ParseValue(value, DataType.string) as string | null;
        break;
      case 'type':
        data.type = ParseValue(value, DataType.enumeration) as TransactionType;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string;
        break;
      case 'amount':
        data.amount = ParseValue(value, DataType.number) as number;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'date':
        data.date = ParseValue(value, DataType.string) as string;
        break;
      case 'sync_status':
        data.sync_status = ParseValue(value, DataType.string) as string;
        break;
      case 'version':
        data.version = ParseValue(value, DataType.number) as number;
        break;
      case 'is_deleted':
        data.is_deleted = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as TransactionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DateUserId fields
 */
function createIndexDateUserId(
  date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, date, 'date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['date', 'user_id'],
    values
  };
}
/**
 * Create index for BankAccountId fields
 */
function createIndexBankAccountId(
  bank_account_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, bank_account_id, 'bank_account_id'),
  ];

  return {
    fields: ['bank_account_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TransactionORM;