// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: financial_report.
// - Entity ID: 102019ae94a709574729d07bd3fda072156.
// - Entity Version: 102019b0cb388b97545831b5a76f4dd021d.
// - Task ID: 693a8c02332fbcb5bc0e621c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for FinancialReportReportType
 */
export enum FinancialReportReportType {
  Unspecified = 0,
  IncomeStatement = 1,
  SpendingAnalysis = 2,
  TaxSummary = 3,
  NetWorth = 4,
}



/**
 * Interface for FinancialReportModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface FinancialReportModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  report_type: FinancialReportReportType;
  report_data: string;
  start_date: string;
  end_date: string;
  generated_at: string;
}

/**
 * ORM class for FinancialReport entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class FinancialReportORM {
  private static instance: FinancialReportORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ae94a709574729d07bd3fda072156';
    this.entityName = 'financial_report';
    this.entityVersion = '102019b0cb388b97545831b5a76f4dd021d';
    this.taskId = '693a8c02332fbcb5bc0e621c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of FinancialReportORM
   */
  public static getInstance(): FinancialReportORM {
    if (!FinancialReportORM.instance) {
      FinancialReportORM.instance = new FinancialReportORM();
    }
    
    return FinancialReportORM.instance;
  }

  /**
   * Get all FinancialReport records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllFinancialReport(): Promise<FinancialReportModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new FinancialReport record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertFinancialReport(data: FinancialReportModel[]): Promise<FinancialReportModel[]> {
    const structured = data.map((item) => CreateData(FinancialReportModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all FinancialReport records
   */
  async purgeAllFinancialReport(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List FinancialReport records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listFinancialReport(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[FinancialReportModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get financial_report by Id index
   * This function gets data by index.
   */
  async getFinancialReportById(
    id: string,
  ): Promise<FinancialReportModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_report by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReportById(
    id: string,
    data: FinancialReportModel
  ): Promise<FinancialReportModel[]> {
    const index = createIndexId(
      id
    );

    const values = FinancialReportModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_report by Id index
   */
  async deleteFinancialReportById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_report by DataCreator index
   * This function gets data by index.
   */
  async getFinancialReportByDataCreator(
    data_creator: string,
  ): Promise<FinancialReportModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_report by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReportByDataCreator(
    data_creator: string,
    data: FinancialReportModel
  ): Promise<FinancialReportModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = FinancialReportModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_report by DataCreator index
   */
  async deleteFinancialReportByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_report by DataUpdater index
   * This function gets data by index.
   */
  async getFinancialReportByDataUpdater(
    data_updater: string,
  ): Promise<FinancialReportModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_report by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReportByDataUpdater(
    data_updater: string,
    data: FinancialReportModel
  ): Promise<FinancialReportModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = FinancialReportModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_report by DataUpdater index
   */
  async deleteFinancialReportByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_report by ReportTypeUserId index
   * This function gets data by index.
   */
  async getFinancialReportByReportTypeUserId(
    report_type: FinancialReportReportType,
    user_id: string,
  ): Promise<FinancialReportModel[]> {
    const index = createIndexReportTypeUserId(
      report_type,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_report by ReportTypeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReportByReportTypeUserId(
    report_type: FinancialReportReportType,
    user_id: string,
    data: FinancialReportModel
  ): Promise<FinancialReportModel[]> {
    const index = createIndexReportTypeUserId(
      report_type,
      user_id
    );

    const values = FinancialReportModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_report by ReportTypeUserId index
   */
  async deleteFinancialReportByReportTypeUserId(
    report_type: FinancialReportReportType,
    user_id: string
  ): Promise<void> {
    const index = createIndexReportTypeUserId(
      report_type,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_report by GeneratedAtUserId index
   * This function gets data by index.
   */
  async getFinancialReportByGeneratedAtUserId(
    generated_at: string,
    user_id: string,
  ): Promise<FinancialReportModel[]> {
    const index = createIndexGeneratedAtUserId(
      generated_at,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_report by GeneratedAtUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReportByGeneratedAtUserId(
    generated_at: string,
    user_id: string,
    data: FinancialReportModel
  ): Promise<FinancialReportModel[]> {
    const index = createIndexGeneratedAtUserId(
      generated_at,
      user_id
    );

    const values = FinancialReportModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_report by GeneratedAtUserId index
   */
  async deleteFinancialReportByGeneratedAtUserId(
    generated_at: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexGeneratedAtUserId(
      generated_at,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to FinancialReportModel data array
   */
  private resultToData(values: Data[]): FinancialReportModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return FinancialReportModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as FinancialReportModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized FinancialReportModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is FinancialReportModel => item !== null);
  }
}

/**
 * Convert FinancialReportModel data to Value array
 */
function FinancialReportModelToValues(data: FinancialReportModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'report_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'report_data', type: DataType.string, defaultValue: '' },
    { key: 'start_date', type: DataType.string, defaultValue: '' },
    { key: 'end_date', type: DataType.string, defaultValue: '' },
    { key: 'generated_at', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof FinancialReportModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to FinancialReportModel data
 */
function FinancialReportModelFromValues(values: Value[]): FinancialReportModel {
  const data: Partial<FinancialReportModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'report_type':
        data.report_type = ParseValue(value, DataType.enumeration) as FinancialReportReportType;
        break;
      case 'report_data':
        data.report_data = ParseValue(value, DataType.string) as string;
        break;
      case 'start_date':
        data.start_date = ParseValue(value, DataType.string) as string;
        break;
      case 'end_date':
        data.end_date = ParseValue(value, DataType.string) as string;
        break;
      case 'generated_at':
        data.generated_at = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as FinancialReportModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ReportTypeUserId fields
 */
function createIndexReportTypeUserId(
  report_type: FinancialReportReportType,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, report_type, 'report_type'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['report_type', 'user_id'],
    values
  };
}
/**
 * Create index for GeneratedAtUserId fields
 */
function createIndexGeneratedAtUserId(
  generated_at: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, generated_at, 'generated_at'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['generated_at', 'user_id'],
    values
  };
}

export default FinancialReportORM;