// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: device_registration.
// - Entity ID: 102019b1614346877efacb71bc87d71517a.
// - Entity Version: 102019b505b2cc97c4e87e620b193838a68.
// - Task ID: 694bdde12e0faedc96c1c26c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for DeviceRegistrationModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DeviceRegistrationModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  device_id: string;
  device_name: string;
  os_type: string;
  last_active_timestamp: string;
  push_token?: string | null;
}

/**
 * ORM class for DeviceRegistration entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DeviceRegistrationORM {
  private static instance: DeviceRegistrationORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1614346877efacb71bc87d71517a';
    this.entityName = 'device_registration';
    this.entityVersion = '102019b505b2cc97c4e87e620b193838a68';
    this.taskId = '694bdde12e0faedc96c1c26c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of DeviceRegistrationORM
   */
  public static getInstance(): DeviceRegistrationORM {
    if (!DeviceRegistrationORM.instance) {
      DeviceRegistrationORM.instance = new DeviceRegistrationORM();
    }
    
    return DeviceRegistrationORM.instance;
  }

  /**
   * Get device_registration by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getDeviceRegistrationByIDs(ids: string[]): Promise<DeviceRegistrationModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete device_registration by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteDeviceRegistrationByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all DeviceRegistration records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDeviceRegistration(): Promise<DeviceRegistrationModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DeviceRegistration record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDeviceRegistration(data: DeviceRegistrationModel[]): Promise<DeviceRegistrationModel[]> {
    const structured = data.map((item) => CreateData(DeviceRegistrationModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DeviceRegistration records
   */
  async purgeAllDeviceRegistration(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DeviceRegistration records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDeviceRegistration(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DeviceRegistrationModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get device_registration by Id index
   * This function gets data by index.
   */
  async getDeviceRegistrationById(
    id: string,
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) device_registration by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDeviceRegistrationById(
    id: string,
    data: DeviceRegistrationModel
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexId(
      id
    );

    const values = DeviceRegistrationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete device_registration by Id index
   */
  async deleteDeviceRegistrationById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get device_registration by DeviceId index
   * This function gets data by index.
   */
  async getDeviceRegistrationByDeviceId(
    device_id: string,
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexDeviceId(
      device_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) device_registration by DeviceId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDeviceRegistrationByDeviceId(
    device_id: string,
    data: DeviceRegistrationModel
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexDeviceId(
      device_id
    );

    const values = DeviceRegistrationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete device_registration by DeviceId index
   */
  async deleteDeviceRegistrationByDeviceId(
    device_id: string
  ): Promise<void> {
    const index = createIndexDeviceId(
      device_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get device_registration by UserId index
   * This function gets data by index.
   */
  async getDeviceRegistrationByUserId(
    user_id: string,
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) device_registration by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDeviceRegistrationByUserId(
    user_id: string,
    data: DeviceRegistrationModel
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = DeviceRegistrationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete device_registration by UserId index
   */
  async deleteDeviceRegistrationByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get device_registration by DataCreator index
   * This function gets data by index.
   */
  async getDeviceRegistrationByDataCreator(
    data_creator: string,
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) device_registration by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDeviceRegistrationByDataCreator(
    data_creator: string,
    data: DeviceRegistrationModel
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DeviceRegistrationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete device_registration by DataCreator index
   */
  async deleteDeviceRegistrationByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get device_registration by DataUpdater index
   * This function gets data by index.
   */
  async getDeviceRegistrationByDataUpdater(
    data_updater: string,
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) device_registration by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDeviceRegistrationByDataUpdater(
    data_updater: string,
    data: DeviceRegistrationModel
  ): Promise<DeviceRegistrationModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DeviceRegistrationModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete device_registration by DataUpdater index
   */
  async deleteDeviceRegistrationByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DeviceRegistrationModel data array
   */
  private resultToData(values: Data[]): DeviceRegistrationModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DeviceRegistrationModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DeviceRegistrationModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DeviceRegistrationModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DeviceRegistrationModel => item !== null);
  }
}

/**
 * Convert DeviceRegistrationModel data to Value array
 */
function DeviceRegistrationModelToValues(data: DeviceRegistrationModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'device_id', type: DataType.string, defaultValue: '' },
    { key: 'device_name', type: DataType.string, defaultValue: '' },
    { key: 'os_type', type: DataType.string, defaultValue: '' },
    { key: 'last_active_timestamp', type: DataType.string, defaultValue: '' },
    { key: 'push_token', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DeviceRegistrationModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DeviceRegistrationModel data
 */
function DeviceRegistrationModelFromValues(values: Value[]): DeviceRegistrationModel {
  const data: Partial<DeviceRegistrationModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'device_id':
        data.device_id = ParseValue(value, DataType.string) as string;
        break;
      case 'device_name':
        data.device_name = ParseValue(value, DataType.string) as string;
        break;
      case 'os_type':
        data.os_type = ParseValue(value, DataType.string) as string;
        break;
      case 'last_active_timestamp':
        data.last_active_timestamp = ParseValue(value, DataType.string) as string;
        break;
      case 'push_token':
        data.push_token = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as DeviceRegistrationModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DeviceId fields
 */
function createIndexDeviceId(
  device_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, device_id, 'device_id'),
  ];

  return {
    fields: ['device_id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default DeviceRegistrationORM;