// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: invoice.
// - Entity ID: 102019b1614346979379436b5127c20404e.
// - Entity Version: 102019b3885245e74489a6d26d33192e397.
// - Task ID: 6945c3c0ee55246be43e8c7f.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for InvoiceStatus
 */
export enum InvoiceStatus {
  Unspecified = 0,
  Draft = 1,
  Sent = 2,
  Paid = 3,
  Overdue = 4,
}



/**
 * Interface for InvoiceModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface InvoiceModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  invoice_number: string;
  client_details: string;
  line_items: string;
  total_amount: number;
  status: InvoiceStatus;
  due_date: string;
  version: number;
}

/**
 * ORM class for Invoice entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class InvoiceORM {
  private static instance: InvoiceORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1614346979379436b5127c20404e';
    this.entityName = 'invoice';
    this.entityVersion = '102019b3885245e74489a6d26d33192e397';
    this.taskId = '6945c3c0ee55246be43e8c7f';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of InvoiceORM
   */
  public static getInstance(): InvoiceORM {
    if (!InvoiceORM.instance) {
      InvoiceORM.instance = new InvoiceORM();
    }
    
    return InvoiceORM.instance;
  }

  /**
   * Get invoice by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getInvoiceByIDs(ids: string[]): Promise<InvoiceModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete invoice by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteInvoiceByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Invoice records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllInvoice(): Promise<InvoiceModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Invoice record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertInvoice(data: InvoiceModel[]): Promise<InvoiceModel[]> {
    const structured = data.map((item) => CreateData(InvoiceModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Invoice records
   */
  async purgeAllInvoice(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Invoice records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listInvoice(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[InvoiceModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get invoice by Id index
   * This function gets data by index.
   */
  async getInvoiceById(
    id: string,
  ): Promise<InvoiceModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) invoice by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInvoiceById(
    id: string,
    data: InvoiceModel
  ): Promise<InvoiceModel[]> {
    const index = createIndexId(
      id
    );

    const values = InvoiceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete invoice by Id index
   */
  async deleteInvoiceById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get invoice by InvoiceNumberUserId index
   * This function gets data by index.
   */
  async getInvoiceByInvoiceNumberUserId(
    invoice_number: string,
    user_id: string,
  ): Promise<InvoiceModel[]> {
    const index = createIndexInvoiceNumberUserId(
      invoice_number,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) invoice by InvoiceNumberUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInvoiceByInvoiceNumberUserId(
    invoice_number: string,
    user_id: string,
    data: InvoiceModel
  ): Promise<InvoiceModel[]> {
    const index = createIndexInvoiceNumberUserId(
      invoice_number,
      user_id
    );

    const values = InvoiceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete invoice by InvoiceNumberUserId index
   */
  async deleteInvoiceByInvoiceNumberUserId(
    invoice_number: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexInvoiceNumberUserId(
      invoice_number,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get invoice by DataCreator index
   * This function gets data by index.
   */
  async getInvoiceByDataCreator(
    data_creator: string,
  ): Promise<InvoiceModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) invoice by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInvoiceByDataCreator(
    data_creator: string,
    data: InvoiceModel
  ): Promise<InvoiceModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = InvoiceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete invoice by DataCreator index
   */
  async deleteInvoiceByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get invoice by DataUpdater index
   * This function gets data by index.
   */
  async getInvoiceByDataUpdater(
    data_updater: string,
  ): Promise<InvoiceModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) invoice by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setInvoiceByDataUpdater(
    data_updater: string,
    data: InvoiceModel
  ): Promise<InvoiceModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = InvoiceModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete invoice by DataUpdater index
   */
  async deleteInvoiceByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to InvoiceModel data array
   */
  private resultToData(values: Data[]): InvoiceModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return InvoiceModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as InvoiceModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized InvoiceModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is InvoiceModel => item !== null);
  }
}

/**
 * Convert InvoiceModel data to Value array
 */
function InvoiceModelToValues(data: InvoiceModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'invoice_number', type: DataType.string, defaultValue: '' },
    { key: 'client_details', type: DataType.string, defaultValue: '' },
    { key: 'line_items', type: DataType.string, defaultValue: '' },
    { key: 'total_amount', type: DataType.number, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'due_date', type: DataType.string, defaultValue: '' },
    { key: 'version', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof InvoiceModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to InvoiceModel data
 */
function InvoiceModelFromValues(values: Value[]): InvoiceModel {
  const data: Partial<InvoiceModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'invoice_number':
        data.invoice_number = ParseValue(value, DataType.string) as string;
        break;
      case 'client_details':
        data.client_details = ParseValue(value, DataType.string) as string;
        break;
      case 'line_items':
        data.line_items = ParseValue(value, DataType.string) as string;
        break;
      case 'total_amount':
        data.total_amount = ParseValue(value, DataType.number) as number;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as InvoiceStatus;
        break;
      case 'due_date':
        data.due_date = ParseValue(value, DataType.string) as string;
        break;
      case 'version':
        data.version = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as InvoiceModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for InvoiceNumberUserId fields
 */
function createIndexInvoiceNumberUserId(
  invoice_number: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, invoice_number, 'invoice_number'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['invoice_number', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default InvoiceORM;