// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: tax_profile.
// - Entity ID: 102019ae94a70957b18837c824f6cf54946.
// - Entity Version: 102019b0cb388b97545831b5a76f4dd021d.
// - Task ID: 693a8c02332fbcb5bc0e621c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for TaxProfileFilingStatus
 */
export enum TaxProfileFilingStatus {
  Unspecified = 0,
  Single = 1,
  MarriedFilingJointly = 2,
  MarriedFilingSeparately = 3,
  HeadOfHousehold = 4,
}



/**
 * Interface for TaxProfileModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TaxProfileModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  jurisdiction: string;
  filing_status: TaxProfileFilingStatus;
  dependents: number;
  estimated_tax_rate: number;
  yearly_income: number;
}

/**
 * ORM class for TaxProfile entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TaxProfileORM {
  private static instance: TaxProfileORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ae94a70957b18837c824f6cf54946';
    this.entityName = 'tax_profile';
    this.entityVersion = '102019b0cb388b97545831b5a76f4dd021d';
    this.taskId = '693a8c02332fbcb5bc0e621c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of TaxProfileORM
   */
  public static getInstance(): TaxProfileORM {
    if (!TaxProfileORM.instance) {
      TaxProfileORM.instance = new TaxProfileORM();
    }
    
    return TaxProfileORM.instance;
  }

  /**
   * Get all TaxProfile records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTaxProfile(): Promise<TaxProfileModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new TaxProfile record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTaxProfile(data: TaxProfileModel[]): Promise<TaxProfileModel[]> {
    const structured = data.map((item) => CreateData(TaxProfileModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all TaxProfile records
   */
  async purgeAllTaxProfile(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List TaxProfile records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTaxProfile(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TaxProfileModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get tax_profile by Id index
   * This function gets data by index.
   */
  async getTaxProfileById(
    id: string,
  ): Promise<TaxProfileModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) tax_profile by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTaxProfileById(
    id: string,
    data: TaxProfileModel
  ): Promise<TaxProfileModel[]> {
    const index = createIndexId(
      id
    );

    const values = TaxProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete tax_profile by Id index
   */
  async deleteTaxProfileById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get tax_profile by DataCreator index
   * This function gets data by index.
   */
  async getTaxProfileByDataCreator(
    data_creator: string,
  ): Promise<TaxProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) tax_profile by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTaxProfileByDataCreator(
    data_creator: string,
    data: TaxProfileModel
  ): Promise<TaxProfileModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TaxProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete tax_profile by DataCreator index
   */
  async deleteTaxProfileByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get tax_profile by DataUpdater index
   * This function gets data by index.
   */
  async getTaxProfileByDataUpdater(
    data_updater: string,
  ): Promise<TaxProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) tax_profile by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTaxProfileByDataUpdater(
    data_updater: string,
    data: TaxProfileModel
  ): Promise<TaxProfileModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TaxProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete tax_profile by DataUpdater index
   */
  async deleteTaxProfileByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get tax_profile by UserId index
   * This function gets data by index.
   */
  async getTaxProfileByUserId(
    user_id: string,
  ): Promise<TaxProfileModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) tax_profile by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTaxProfileByUserId(
    user_id: string,
    data: TaxProfileModel
  ): Promise<TaxProfileModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = TaxProfileModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete tax_profile by UserId index
   */
  async deleteTaxProfileByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TaxProfileModel data array
   */
  private resultToData(values: Data[]): TaxProfileModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TaxProfileModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TaxProfileModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TaxProfileModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TaxProfileModel => item !== null);
  }
}

/**
 * Convert TaxProfileModel data to Value array
 */
function TaxProfileModelToValues(data: TaxProfileModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'jurisdiction', type: DataType.string, defaultValue: '' },
    { key: 'filing_status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'dependents', type: DataType.number, defaultValue: 0 },
    { key: 'estimated_tax_rate', type: DataType.number, defaultValue: 0 },
    { key: 'yearly_income', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TaxProfileModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TaxProfileModel data
 */
function TaxProfileModelFromValues(values: Value[]): TaxProfileModel {
  const data: Partial<TaxProfileModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'jurisdiction':
        data.jurisdiction = ParseValue(value, DataType.string) as string;
        break;
      case 'filing_status':
        data.filing_status = ParseValue(value, DataType.enumeration) as TaxProfileFilingStatus;
        break;
      case 'dependents':
        data.dependents = ParseValue(value, DataType.number) as number;
        break;
      case 'estimated_tax_rate':
        data.estimated_tax_rate = ParseValue(value, DataType.number) as number;
        break;
      case 'yearly_income':
        data.yearly_income = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as TaxProfileModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}

export default TaxProfileORM;