// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: bank_connection.
// - Entity ID: 102019b1614346a70ae92cbe32a17eb5485.
// - Entity Version: 102019b505b2cc97c4e87e620b193838a68.
// - Task ID: 694bdde12e0faedc96c1c26c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for BankConnectionStatus
 */
export enum BankConnectionStatus {
  Unspecified = 0,
  Active = 1,
  Disconnected = 2,
  Error = 3,
  Pending = 4,
}



/**
 * Interface for BankConnectionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BankConnectionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  provider_name: string;
  access_token: string;
  refresh_token?: string | null;
  status: BankConnectionStatus;
  last_sync_timestamp?: string | null;
  error_logs?: string | null;
}

/**
 * ORM class for BankConnection entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BankConnectionORM {
  private static instance: BankConnectionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1614346a70ae92cbe32a17eb5485';
    this.entityName = 'bank_connection';
    this.entityVersion = '102019b505b2cc97c4e87e620b193838a68';
    this.taskId = '694bdde12e0faedc96c1c26c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of BankConnectionORM
   */
  public static getInstance(): BankConnectionORM {
    if (!BankConnectionORM.instance) {
      BankConnectionORM.instance = new BankConnectionORM();
    }
    
    return BankConnectionORM.instance;
  }

  /**
   * Get bank_connection by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getBankConnectionByIDs(ids: string[]): Promise<BankConnectionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bank_connection by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteBankConnectionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all BankConnection records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBankConnection(): Promise<BankConnectionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new BankConnection record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBankConnection(data: BankConnectionModel[]): Promise<BankConnectionModel[]> {
    const structured = data.map((item) => CreateData(BankConnectionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all BankConnection records
   */
  async purgeAllBankConnection(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List BankConnection records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBankConnection(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BankConnectionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get bank_connection by Id index
   * This function gets data by index.
   */
  async getBankConnectionById(
    id: string,
  ): Promise<BankConnectionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bank_connection by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBankConnectionById(
    id: string,
    data: BankConnectionModel
  ): Promise<BankConnectionModel[]> {
    const index = createIndexId(
      id
    );

    const values = BankConnectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bank_connection by Id index
   */
  async deleteBankConnectionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bank_connection by UserId index
   * This function gets data by index.
   */
  async getBankConnectionByUserId(
    user_id: string,
  ): Promise<BankConnectionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bank_connection by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBankConnectionByUserId(
    user_id: string,
    data: BankConnectionModel
  ): Promise<BankConnectionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = BankConnectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bank_connection by UserId index
   */
  async deleteBankConnectionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bank_connection by DataCreator index
   * This function gets data by index.
   */
  async getBankConnectionByDataCreator(
    data_creator: string,
  ): Promise<BankConnectionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bank_connection by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBankConnectionByDataCreator(
    data_creator: string,
    data: BankConnectionModel
  ): Promise<BankConnectionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BankConnectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bank_connection by DataCreator index
   */
  async deleteBankConnectionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get bank_connection by DataUpdater index
   * This function gets data by index.
   */
  async getBankConnectionByDataUpdater(
    data_updater: string,
  ): Promise<BankConnectionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) bank_connection by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBankConnectionByDataUpdater(
    data_updater: string,
    data: BankConnectionModel
  ): Promise<BankConnectionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BankConnectionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete bank_connection by DataUpdater index
   */
  async deleteBankConnectionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BankConnectionModel data array
   */
  private resultToData(values: Data[]): BankConnectionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BankConnectionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BankConnectionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BankConnectionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BankConnectionModel => item !== null);
  }
}

/**
 * Convert BankConnectionModel data to Value array
 */
function BankConnectionModelToValues(data: BankConnectionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'provider_name', type: DataType.string, defaultValue: '' },
    { key: 'access_token', type: DataType.string, defaultValue: '' },
    { key: 'refresh_token', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'last_sync_timestamp', type: DataType.string, defaultValue: null },
    { key: 'error_logs', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BankConnectionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BankConnectionModel data
 */
function BankConnectionModelFromValues(values: Value[]): BankConnectionModel {
  const data: Partial<BankConnectionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'provider_name':
        data.provider_name = ParseValue(value, DataType.string) as string;
        break;
      case 'access_token':
        data.access_token = ParseValue(value, DataType.string) as string;
        break;
      case 'refresh_token':
        data.refresh_token = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as BankConnectionStatus;
        break;
      case 'last_sync_timestamp':
        data.last_sync_timestamp = ParseValue(value, DataType.string) as string | null;
        break;
      case 'error_logs':
        data.error_logs = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as BankConnectionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default BankConnectionORM;