// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: conflict_resolution.
// - Entity ID: 102019b161434687f1ca4709337da974e6b.
// - Entity Version: 102019b505b2cc97c4e87e620b193838a68.
// - Task ID: 694bdde12e0faedc96c1c26c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ConflictResolutionResolutionStrategy
 */
export enum ConflictResolutionResolutionStrategy {
  Unspecified = 0,
  LastWriteWins = 1,
  Manual = 2,
  Merge = 3,
}



/**
 * Interface for ConflictResolutionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ConflictResolutionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  entity_type: string;
  entity_id: string;
  conflicting_versions: string;
  resolution_strategy: ConflictResolutionResolutionStrategy;
  resolved_status: boolean;
}

/**
 * ORM class for ConflictResolution entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ConflictResolutionORM {
  private static instance: ConflictResolutionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b161434687f1ca4709337da974e6b';
    this.entityName = 'conflict_resolution';
    this.entityVersion = '102019b505b2cc97c4e87e620b193838a68';
    this.taskId = '694bdde12e0faedc96c1c26c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of ConflictResolutionORM
   */
  public static getInstance(): ConflictResolutionORM {
    if (!ConflictResolutionORM.instance) {
      ConflictResolutionORM.instance = new ConflictResolutionORM();
    }
    
    return ConflictResolutionORM.instance;
  }

  /**
   * Get conflict_resolution by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getConflictResolutionByIDs(ids: string[]): Promise<ConflictResolutionModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conflict_resolution by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteConflictResolutionByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all ConflictResolution records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllConflictResolution(): Promise<ConflictResolutionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ConflictResolution record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertConflictResolution(data: ConflictResolutionModel[]): Promise<ConflictResolutionModel[]> {
    const structured = data.map((item) => CreateData(ConflictResolutionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ConflictResolution records
   */
  async purgeAllConflictResolution(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ConflictResolution records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listConflictResolution(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ConflictResolutionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get conflict_resolution by Id index
   * This function gets data by index.
   */
  async getConflictResolutionById(
    id: string,
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conflict_resolution by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConflictResolutionById(
    id: string,
    data: ConflictResolutionModel
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexId(
      id
    );

    const values = ConflictResolutionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conflict_resolution by Id index
   */
  async deleteConflictResolutionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conflict_resolution by EntityIdEntityType index
   * This function gets data by index.
   */
  async getConflictResolutionByEntityIdEntityType(
    entity_id: string,
    entity_type: string,
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexEntityIdEntityType(
      entity_id,
      entity_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conflict_resolution by EntityIdEntityType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConflictResolutionByEntityIdEntityType(
    entity_id: string,
    entity_type: string,
    data: ConflictResolutionModel
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexEntityIdEntityType(
      entity_id,
      entity_type
    );

    const values = ConflictResolutionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conflict_resolution by EntityIdEntityType index
   */
  async deleteConflictResolutionByEntityIdEntityType(
    entity_id: string,
    entity_type: string
  ): Promise<void> {
    const index = createIndexEntityIdEntityType(
      entity_id,
      entity_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conflict_resolution by DataCreator index
   * This function gets data by index.
   */
  async getConflictResolutionByDataCreator(
    data_creator: string,
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conflict_resolution by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConflictResolutionByDataCreator(
    data_creator: string,
    data: ConflictResolutionModel
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ConflictResolutionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conflict_resolution by DataCreator index
   */
  async deleteConflictResolutionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get conflict_resolution by DataUpdater index
   * This function gets data by index.
   */
  async getConflictResolutionByDataUpdater(
    data_updater: string,
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) conflict_resolution by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setConflictResolutionByDataUpdater(
    data_updater: string,
    data: ConflictResolutionModel
  ): Promise<ConflictResolutionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ConflictResolutionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete conflict_resolution by DataUpdater index
   */
  async deleteConflictResolutionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ConflictResolutionModel data array
   */
  private resultToData(values: Data[]): ConflictResolutionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ConflictResolutionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ConflictResolutionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ConflictResolutionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ConflictResolutionModel => item !== null);
  }
}

/**
 * Convert ConflictResolutionModel data to Value array
 */
function ConflictResolutionModelToValues(data: ConflictResolutionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'entity_type', type: DataType.string, defaultValue: '' },
    { key: 'entity_id', type: DataType.string, defaultValue: '' },
    { key: 'conflicting_versions', type: DataType.string, defaultValue: '' },
    { key: 'resolution_strategy', type: DataType.enumeration, defaultValue: 0 },
    { key: 'resolved_status', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ConflictResolutionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ConflictResolutionModel data
 */
function ConflictResolutionModelFromValues(values: Value[]): ConflictResolutionModel {
  const data: Partial<ConflictResolutionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'entity_type':
        data.entity_type = ParseValue(value, DataType.string) as string;
        break;
      case 'entity_id':
        data.entity_id = ParseValue(value, DataType.string) as string;
        break;
      case 'conflicting_versions':
        data.conflicting_versions = ParseValue(value, DataType.string) as string;
        break;
      case 'resolution_strategy':
        data.resolution_strategy = ParseValue(value, DataType.enumeration) as ConflictResolutionResolutionStrategy;
        break;
      case 'resolved_status':
        data.resolved_status = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as ConflictResolutionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for EntityIdEntityType fields
 */
function createIndexEntityIdEntityType(
  entity_id: string,
  entity_type: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, entity_id, 'entity_id'),
    CreateValue(DataType.string, entity_type, 'entity_type'),
  ];

  return {
    fields: ['entity_id', 'entity_type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default ConflictResolutionORM;