// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: financial_reminder.
// - Entity ID: 102019ae94a709570349fbe96a64e7d8b1c.
// - Entity Version: 102019b13f7f968713f9fab43b64e02a910.
// - Task ID: 693c684af9f9f13be389bb2f.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for FinancialReminderFrequency
 */
export enum FinancialReminderFrequency {
  Unspecified = 0,
  OneTime = 1,
  Daily = 2,
  Weekly = 3,
  Monthly = 4,
  Yearly = 5,
}



/**
 * Interface for FinancialReminderModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface FinancialReminderModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  title: string;
  description?: string | null;
  due_date: string;
  frequency: FinancialReminderFrequency;
  is_completed: boolean;
  category?: string | null;
}

/**
 * ORM class for FinancialReminder entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class FinancialReminderORM {
  private static instance: FinancialReminderORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019ae94a709570349fbe96a64e7d8b1c';
    this.entityName = 'financial_reminder';
    this.entityVersion = '102019b13f7f968713f9fab43b64e02a910';
    this.taskId = '693c684af9f9f13be389bb2f';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of FinancialReminderORM
   */
  public static getInstance(): FinancialReminderORM {
    if (!FinancialReminderORM.instance) {
      FinancialReminderORM.instance = new FinancialReminderORM();
    }
    
    return FinancialReminderORM.instance;
  }

  /**
   * Get all FinancialReminder records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllFinancialReminder(): Promise<FinancialReminderModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new FinancialReminder record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertFinancialReminder(data: FinancialReminderModel[]): Promise<FinancialReminderModel[]> {
    const structured = data.map((item) => CreateData(FinancialReminderModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all FinancialReminder records
   */
  async purgeAllFinancialReminder(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List FinancialReminder records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listFinancialReminder(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[FinancialReminderModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get financial_reminder by Id index
   * This function gets data by index.
   */
  async getFinancialReminderById(
    id: string,
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_reminder by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReminderById(
    id: string,
    data: FinancialReminderModel
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexId(
      id
    );

    const values = FinancialReminderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_reminder by Id index
   */
  async deleteFinancialReminderById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_reminder by DataCreator index
   * This function gets data by index.
   */
  async getFinancialReminderByDataCreator(
    data_creator: string,
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_reminder by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReminderByDataCreator(
    data_creator: string,
    data: FinancialReminderModel
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = FinancialReminderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_reminder by DataCreator index
   */
  async deleteFinancialReminderByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_reminder by DataUpdater index
   * This function gets data by index.
   */
  async getFinancialReminderByDataUpdater(
    data_updater: string,
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_reminder by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReminderByDataUpdater(
    data_updater: string,
    data: FinancialReminderModel
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = FinancialReminderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_reminder by DataUpdater index
   */
  async deleteFinancialReminderByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_reminder by DueDateUserId index
   * This function gets data by index.
   */
  async getFinancialReminderByDueDateUserId(
    due_date: string,
    user_id: string,
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexDueDateUserId(
      due_date,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_reminder by DueDateUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReminderByDueDateUserId(
    due_date: string,
    user_id: string,
    data: FinancialReminderModel
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexDueDateUserId(
      due_date,
      user_id
    );

    const values = FinancialReminderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_reminder by DueDateUserId index
   */
  async deleteFinancialReminderByDueDateUserId(
    due_date: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexDueDateUserId(
      due_date,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get financial_reminder by IsCompletedUserId index
   * This function gets data by index.
   */
  async getFinancialReminderByIsCompletedUserId(
    is_completed: boolean,
    user_id: string,
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexIsCompletedUserId(
      is_completed,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) financial_reminder by IsCompletedUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setFinancialReminderByIsCompletedUserId(
    is_completed: boolean,
    user_id: string,
    data: FinancialReminderModel
  ): Promise<FinancialReminderModel[]> {
    const index = createIndexIsCompletedUserId(
      is_completed,
      user_id
    );

    const values = FinancialReminderModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete financial_reminder by IsCompletedUserId index
   */
  async deleteFinancialReminderByIsCompletedUserId(
    is_completed: boolean,
    user_id: string
  ): Promise<void> {
    const index = createIndexIsCompletedUserId(
      is_completed,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to FinancialReminderModel data array
   */
  private resultToData(values: Data[]): FinancialReminderModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return FinancialReminderModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as FinancialReminderModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized FinancialReminderModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is FinancialReminderModel => item !== null);
  }
}

/**
 * Convert FinancialReminderModel data to Value array
 */
function FinancialReminderModelToValues(data: FinancialReminderModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'due_date', type: DataType.string, defaultValue: '' },
    { key: 'frequency', type: DataType.enumeration, defaultValue: 0 },
    { key: 'is_completed', type: DataType.boolean, defaultValue: false },
    { key: 'category', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof FinancialReminderModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to FinancialReminderModel data
 */
function FinancialReminderModelFromValues(values: Value[]): FinancialReminderModel {
  const data: Partial<FinancialReminderModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'due_date':
        data.due_date = ParseValue(value, DataType.string) as string;
        break;
      case 'frequency':
        data.frequency = ParseValue(value, DataType.enumeration) as FinancialReminderFrequency;
        break;
      case 'is_completed':
        data.is_completed = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as FinancialReminderModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for DueDateUserId fields
 */
function createIndexDueDateUserId(
  due_date: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, due_date, 'due_date'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['due_date', 'user_id'],
    values
  };
}
/**
 * Create index for IsCompletedUserId fields
 */
function createIndexIsCompletedUserId(
  is_completed: boolean,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_completed, 'is_completed'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['is_completed', 'user_id'],
    values
  };
}

export default FinancialReminderORM;