// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: sync_metadata.
// - Entity ID: 102019b1614346a742ba58ce4dcc9ba6045.
// - Entity Version: 102019b505b2cc97c4e87e620b193838a68.
// - Task ID: 694bdde12e0faedc96c1c26c.
// - Task Root ID: 69317a33ad50e9e8016841da.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for SyncMetadataModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface SyncMetadataModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  device_id: string;
  entity_type: string;
  last_sync_timestamp: string;
  sync_version: number;
  conflict_queue?: string | null;
}

/**
 * ORM class for SyncMetadata entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class SyncMetadataORM {
  private static instance: SyncMetadataORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019b1614346a742ba58ce4dcc9ba6045';
    this.entityName = 'sync_metadata';
    this.entityVersion = '102019b505b2cc97c4e87e620b193838a68';
    this.taskId = '694bdde12e0faedc96c1c26c';
    this.taskRootId = '69317a33ad50e9e8016841da';
  }

  /**
   * Get singleton instance of SyncMetadataORM
   */
  public static getInstance(): SyncMetadataORM {
    if (!SyncMetadataORM.instance) {
      SyncMetadataORM.instance = new SyncMetadataORM();
    }
    
    return SyncMetadataORM.instance;
  }

  /**
   * Get sync_metadata by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getSyncMetadataByIDs(ids: string[]): Promise<SyncMetadataModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sync_metadata by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteSyncMetadataByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all SyncMetadata records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllSyncMetadata(): Promise<SyncMetadataModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new SyncMetadata record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertSyncMetadata(data: SyncMetadataModel[]): Promise<SyncMetadataModel[]> {
    const structured = data.map((item) => CreateData(SyncMetadataModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all SyncMetadata records
   */
  async purgeAllSyncMetadata(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List SyncMetadata records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listSyncMetadata(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[SyncMetadataModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get sync_metadata by Id index
   * This function gets data by index.
   */
  async getSyncMetadataById(
    id: string,
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sync_metadata by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSyncMetadataById(
    id: string,
    data: SyncMetadataModel
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexId(
      id
    );

    const values = SyncMetadataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sync_metadata by Id index
   */
  async deleteSyncMetadataById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sync_metadata by DeviceIdEntityTypeUserId index
   * This function gets data by index.
   */
  async getSyncMetadataByDeviceIdEntityTypeUserId(
    device_id: string,
    entity_type: string,
    user_id: string,
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexDeviceIdEntityTypeUserId(
      device_id,
      entity_type,
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sync_metadata by DeviceIdEntityTypeUserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSyncMetadataByDeviceIdEntityTypeUserId(
    device_id: string,
    entity_type: string,
    user_id: string,
    data: SyncMetadataModel
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexDeviceIdEntityTypeUserId(
      device_id,
      entity_type,
      user_id
    );

    const values = SyncMetadataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sync_metadata by DeviceIdEntityTypeUserId index
   */
  async deleteSyncMetadataByDeviceIdEntityTypeUserId(
    device_id: string,
    entity_type: string,
    user_id: string
  ): Promise<void> {
    const index = createIndexDeviceIdEntityTypeUserId(
      device_id,
      entity_type,
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sync_metadata by DataCreator index
   * This function gets data by index.
   */
  async getSyncMetadataByDataCreator(
    data_creator: string,
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sync_metadata by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSyncMetadataByDataCreator(
    data_creator: string,
    data: SyncMetadataModel
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = SyncMetadataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sync_metadata by DataCreator index
   */
  async deleteSyncMetadataByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get sync_metadata by DataUpdater index
   * This function gets data by index.
   */
  async getSyncMetadataByDataUpdater(
    data_updater: string,
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) sync_metadata by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setSyncMetadataByDataUpdater(
    data_updater: string,
    data: SyncMetadataModel
  ): Promise<SyncMetadataModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = SyncMetadataModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete sync_metadata by DataUpdater index
   */
  async deleteSyncMetadataByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to SyncMetadataModel data array
   */
  private resultToData(values: Data[]): SyncMetadataModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return SyncMetadataModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as SyncMetadataModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized SyncMetadataModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is SyncMetadataModel => item !== null);
  }
}

/**
 * Convert SyncMetadataModel data to Value array
 */
function SyncMetadataModelToValues(data: SyncMetadataModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'device_id', type: DataType.string, defaultValue: '' },
    { key: 'entity_type', type: DataType.string, defaultValue: '' },
    { key: 'last_sync_timestamp', type: DataType.string, defaultValue: '' },
    { key: 'sync_version', type: DataType.number, defaultValue: 0 },
    { key: 'conflict_queue', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof SyncMetadataModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to SyncMetadataModel data
 */
function SyncMetadataModelFromValues(values: Value[]): SyncMetadataModel {
  const data: Partial<SyncMetadataModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'device_id':
        data.device_id = ParseValue(value, DataType.string) as string;
        break;
      case 'entity_type':
        data.entity_type = ParseValue(value, DataType.string) as string;
        break;
      case 'last_sync_timestamp':
        data.last_sync_timestamp = ParseValue(value, DataType.string) as string;
        break;
      case 'sync_version':
        data.sync_version = ParseValue(value, DataType.number) as number;
        break;
      case 'conflict_queue':
        data.conflict_queue = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as SyncMetadataModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DeviceIdEntityTypeUserId fields
 */
function createIndexDeviceIdEntityTypeUserId(
  device_id: string,
  entity_type: string,
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, device_id, 'device_id'),
    CreateValue(DataType.string, entity_type, 'entity_type'),
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['device_id', 'entity_type', 'user_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default SyncMetadataORM;